services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ (AMQP protocol)
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  frame_reader:
    build: ./frame_reader
    container_name: frame_reader
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - shared-data:/app/shared
      - ${VIDEO_SOURCE:-./shared/Sah w b3dha ghalt (2).mp4}:/app/video_source.mp4
    environment:
      - RABBITMQ_HOST=rabbitmq
      - VIDEO_SOURCE=/app/video_source.mp4

  detector:
    build: ./detection_service
    container_name: detector
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - shared-data:/app/shared
      - ./shared:/app/weights
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MODEL_PATH=/app/weights/best.pt
      - DB_PATH=/app/shared/violations.db
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [ gpu ] # requires Docker with GPU support

  streamer:
    build: ./streaming_service
    container_name: streamer
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - shared-data:/app/shared
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_PATH=/app/shared/violations.db

volumes:
  # Define a named volume for shared data
  shared-data:
